<?php
session_start();
$companyName = $_SESSION['company_name'] ?? $_SESSION['username'] ?? 'Azienda cliente';
$systemId = $_GET['id'] ?? 1;
$systemName = $_SESSION['irrigation_systems'][$systemId - 1]['name'] ?? 'Impianto principale';
$days = ['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'];
$schedule = $_SESSION['schedule'] ?? ['19:45','NO','NO','NO','20:00','NO','NO'];
$soil = $_SESSION['soil_readings'] ?? [42, 47, 45, 53, 50, 57, 61, 58, 66, 63, 69, 72];
$air = $_SESSION['air_readings'] ?? [55, 57, 54, 59, 62, 60, 64, 67, 65, 68, 70, 69];
$rain = $_SESSION['rain_readings'] ?? [2, 0, 4, 0, 8, 5, 1, 0, 12, 7, 3, 0];
function esc($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function points($values, $w=720, $h=180) { $max=max($values) ?: 1; $min=min($values); $range=max($max-$min,1); $step=$w/(count($values)-1); $out=[]; foreach($values as $i=>$v) $out[]=round($i*$step,1).','.round($h-(($v-$min)/$range)*($h-24)-12,1); return implode(' ',$out); }
?><!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= esc($systemName) ?> · Smart Irrigation</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"></head><body>
<div class="app-shell"><main class="main-content detail-content"><header class="topbar"><div><a class="back-link" href="dashboard_home.php">← Tutti i sistemi</a><h1><?= esc($systemName) ?></h1><p class="muted">Monitoraggio e controllo dell'impianto</p></div><div class="logo-circle">💧</div></header><div class="rule"></div>
<section class="schedule-section"><div class="section-heading"><div><span class="eyebrow">CONTROLLO</span><h2>Schedulazione</h2><p class="muted">Imposta i giorni e gli orari di irrigazione settimanale.</p></div><button class="primary-button" form="schedule-form">Salva modifiche</button></div><form id="schedule-form" method="post" action="salva_schedulazione.php" class="schedule-panel"><input type="hidden" name="system_id" value="<?= esc($systemId) ?>"><?php foreach($days as $i=>$day): ?><label class="day-row"><span class="day-name"><?= esc($day) ?></span><input type="time" name="schedule[<?= $i ?>]" value="<?= $schedule[$i] !== 'NO' ? esc($schedule[$i]) : '' ?>"><span class="schedule-value"><?= esc($schedule[$i]) ?></span></label><?php endforeach; ?></form></section>
<section class="stats-section"><div class="section-heading"><div><span class="eyebrow">DATI SENSORI</span><h2>Statistiche</h2></div><span class="live-pill"><i></i> Dati aggiornati</span></div>
<?php $charts=[['Umidità terreno','Ultime 24 ore','%',$soil,'chart-blue'],['Umidità aria','Ultime 24 ore','%',$air,'chart-teal'],['Frequenza piogge','Ultime 24 ore','mm',$rain,'chart-purple']]; foreach($charts as [$title,$period,$unit,$values,$color]): ?><article class="chart-card"><div class="chart-heading"><div><h3><?= $title ?></h3><p class="muted"><?= $period ?> · <?= $unit ?></p></div><strong><?= esc(end($values)) ?> <small><?= $unit ?></small></strong></div><svg class="chart <?= $color ?>" viewBox="0 0 720 180" preserveAspectRatio="none" role="img" aria-label="Grafico <?= $title ?>"><defs><linearGradient id="fill<?= $title[0] ?>" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-opacity=".28"/><stop offset="1" stop-opacity="0"/></linearGradient></defs><path class="area" d="M 0 168 L <?= points($values) ?> L 720 168 Z"/><polyline points="<?= points($values) ?>"/></svg><div class="chart-labels"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>Ora</span></div></article><?php endforeach; ?></section>
</main><aside class="sidebar"><div class="sidebar-brand"><span class="brand-mark small">💧</span><span>Smart<br><strong>Irrigation</strong></span></div><div class="sidebar-separator"></div><nav><a class="side-link active" href="dashboard_home.php"><span>⌂</span>Home</a><a class="side-link" href="#statistics"><span>◔</span>Statistiche generali</a><a class="side-link" href="#ai"><span>✦</span>Consigli AI</a><a class="side-link" href="#contact"><span>↗</span>Contattaci</a></nav><a class="side-link logout" href="logout.php"><span>↪</span>Log-out</a></aside></div></body></html>
